apiVersion: v1
kind: ConfigMap
metadata:
  name: config-testk8s
  namespace: default
  labels:
    app: testk8s
    component: configuration
    version: v1.0.0
data:
  configmap.properties: |
    k8s.configmap.name=Anna
  application-prod.properties: |
    management.endpoints.web.exposure.include=health,info,metrics,prometheus
    management.endpoint.health.show-details=when-authorized
    management.endpoint.health.probes.enabled=true
    management.health.livenessstate.enabled=true
    management.health.readinessstate.enabled=true
    logging.level.it.alf.testk8s=INFO
    logging.level.org.springframework.web=INFO
    server.tomcat.max-threads=200
    server.tomcat.min-spare-threads=10