apiVersion: v1
kind: ServiceAccount
metadata:
  name: testk8s
  namespace: default
  labels:
    app: testk8s
    component: backend
automountServiceAccountToken: false
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: testk8s-role
  labels:
    app: testk8s
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: testk8s-rolebinding
  namespace: default
  labels:
    app: testk8s
subjects:
- kind: ServiceAccount
  name: testk8s
  namespace: default
roleRef:
  kind: Role
  name: testk8s-role
  apiGroup: rbac.authorization.k8s.io